apiVersion: v1 
kind: PersistentVolume
metadata:
  name: local-pv-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /tmp/data/pv-1

---

apiVersion: v1 
kind: PersistentVolume
metadata:
  name: local-pv-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /tmp/data/pv-2